### ISSUE TITLE
Delcarative config empty http_methods gives an issue

### ISSUE THREAD

**Issue by surfer190** [Kong/kong-plugin-request-transformer#10]
In my config I have:

```
  plugins:
  - name: request-transformer
    config:
      add:
        body: []
        headers: []
        querystring:
        - api_token:xxx
        - fmt:json
      append:
        body: []
        headers: []
        querystring: []
      http_method: ''
      remove:
        body: []
        headers: []
        querystring: []
      rename:
        body: []
        headers: []
        querystring: []
      replace:
        body: []
        headers: []
        querystring: []
    enabled: true
    run_on: first
    protocols:
    - http
    - https
```

I get:
```

Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64:
in 'services':
   - in entry 1 of 'services':
     in 'plugins':
      - in entry 1 of 'plugins':
        in 'config':
          in 'http_method': length must be at least 1
 stack traceback:
         [C]: in function 'error'
         /usr/local/share/lua/5.1/kong/init.lua:432: in
         init_by_lua:3: in main chunk
   Run with --v (verbose) or --vv (debug) for more deta
```

I had to set it to       `http_method: 'GET'`
