### ISSUE TITLE
Error filling in defaults for plugin: kong-plugin-request-transformer

### ISSUE THREAD

**Issue by anshudutta** [Kong/kong-plugin-request-transformer#14]
I have the plugin in kubernetes
```
apiVersion: configuration.konghq.com/v1
  config:
    replace.uri: /oauth2/auth
  kind: KongPlugin
  metadata:
    name: kong-plugin-request-transformer
  plugin: kong-plugin-request-transformer
```
The plugin is installed in the kong image like 
```
luarocks install kong-plugin-request-transformer
```
Also specified the `values.yaml` helm chart like so
```
plugins:
      configMaps:
      - pluginName: "request-transformer"
        name: "kong-plugin-request-transformer"
```
Its used in ingess like so
```
annotations:
        kubernetes.io/ingress.class: kong
        plugins.konghq.com: kong-plugin-request-transformer
```
The functionality works but I get the error in kong-ingress logs
```
E0110 03:09:17.862183       1 kong.go:254] error filling in defaults for plugin: kong-plugin-request-transformer
```
