### ISSUE TITLE
bug: runtime error for adding header

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [Kong/kong-plugin-request-transformer#25]
I'm getting a runtime error testing this header adding config:

```
plugins:
- name: request-transformer
  config:
    add:
      headers:
      - x-user-agent:$(type(headers["User-Agent"]) == "table" and headers["User-Agent"][1] or headers["User-Agent"])
```

Here's the error:

```
2020/08/21 19:50:34 [error] 29#0: *123 lua coroutine: runtime error: ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:211: bad argument #2 to '(for generator)' (number expected, got string)
stack traceback:
coroutine 0:
   [C]: in function '(for generator)'
   ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:211: in function 'transform_headers'
   ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:512: in function 'execute'
   ...are/lua/5.1/kong/plugins/request-transformer/handler.lua:11: in function <...are/lua/5.1/kong/plugins/request-transformer/handler.lua:10>
coroutine 1:
   [C]: in function 'resume'
   coroutine.wrap:21: in function <coroutine.wrap:21>
   /usr/local/share/lua/5.1/kong/init.lua:705: in function 'access'
   access_by_lua(nginx-kong.conf:95):2: in main chunk, client: 172.24.0.6, server: kong, request: "GET /test-service HTTP/1.1", host: "kong:8443"
2020/08/21 19:50:34 [error] 29#0: *123 [kong] init.lua:707 [request-transformer] ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:211: bad argument #2 to '(for generator)' (number expected, got string), client: 172.24.0.6, server: kong, request: "GET /test-service HTTP/1.1", host: "kong:8443"
```
